from ..interfaces import HalfRange as HalfRange
from typing import Any, Dict, Union

def auto_column_width(tab_id: int, rng: HalfRange) -> Dict[str, Any]: ...
def append_rows(tab_id: int, num_rows: int) -> Dict[str, Any]: ...
def insert_rows(tab_id: int, num_rows: int, at_row: int) -> Dict[str, Any]: ...
def delete_rows(tab_id: int, rng: HalfRange) -> Dict[str, Any]: ...
def freeze(
    tab_id: int, rows: int, *, columns: Union[int, None] = ...
) -> Dict[str, Any]: ...
def append_columns(tab_id: int, num_cols: int) -> Dict[str, Any]: ...
def insert_columns(tab_id: int, num_cols: int, at_col: int) -> Dict[str, Any]: ...
def delete_columns(tab_id: int, rng: HalfRange) -> Dict[str, Any]: ...
