name: Upload Autodrive Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      - name: Build package
        run: poetry run poetry build
      - name: Publish package
        run: poetry run poetry publish
